### PR TITLE
CSS3

### PR DESCRIPTION
**Pull request by dansantander**
This is the first pull request for the Positioning and Floating project. 
This project is about how to move different elements around the page mainly using CSS. With CSS positioning and floating we greatly reduce on the  baggage of HTML tags we have to write.

### CODE REVIEW

**Review by pelzolga123 — CHANGES_REQUESTED** [review]
Project requires changes.

**Comment by pelzolga123** [comment]
## Hi Team!  
### Your project looks :+1: amazing!

Here are things you need to change before this project can be approved:

* [ ] Pull Request should have meaningful title and a short description ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
* [ ] Your .stickler.yml file is present but not configured. You need to fix that.
* [ ] Footer should have a fixed position (it sticks to the bottom part of the screen) ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0))
image
#### Bottom part
* [ ] Should contain links to other articles with image previews on the leftmost side ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0))
* [ ] Should contain links to more popular articles on the rightmost side ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0))
image

### Please kindly fix the above issues and send another code review request.

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

**Review by fatymahmed — CHANGES_REQUESTED** [review]
## Hi @dansantander @Genius8,
Good job on making some of the changes requested by the previous TSE 👏👏, however, for this project to be approved, you need to make all changes.
- [ ] You have stickler files, but it is not yet configured, check [this guide](https://github.com/microverseinc/linters-config/blob/master/css/.stickler.yml) on how to do so, you might have missed something.
- [ ]  Your Pull Request should have a meaningful title and a short description [screenshot from Pathwright](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png)

### Kindly make the suggested changes and request for another code review.
### Status: Changes Required
_Feel free to reach out to me on slack(Fatima) if you have any questions, I'd be happy to help._

**Review by fatymahmed — APPROVED** [review]
## Hi @dansantander @Genius8, 
### Great job adding stickler 🎉🎉

### It's a 👍🏾 from me!
## ✔️ Approved!

Good luck with your next projects.
 _Don't forget to submit your project completion form_

**Pull request merged**
